name: Nuget MAD.Extensions.EFCore6

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - 'MAD.Extensions.EFCore6/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:          
          dotnet-version: '6.0.x' # SDK Version to use.          
      - name: Restore dependencies
        run: dotnet restore MAD.Extensions.EFCore6
      - name: Build
        run: dotnet build MAD.Extensions.EFCore6 --no-restore
      - name: Test
        run: dotnet test MAD.Extensions.EFCore6 --no-build --verbosity normal
      - name: Pack
        run: dotnet pack --configuration Release MAD.Extensions.EFCore6
      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json
